
  version: '3.8'

  services:
    postgres:
      image: postgres:15
      container_name: sistema-update-db
      environment:
        POSTGRES_DB: sistema_update
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin123
        POSTGRES_HOST_AUTH_METHOD: trust
      ports:
        - "5433:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./sql:/docker-entrypoint-initdb.d
      restart: unless-stopped

  volumes:
    postgres_data:
